### PR TITLE
update DataAccess

### PR DESCRIPTION
**Pull request by mattfred**

### CODE REVIEW

**Comment by mattfred** [comment]
@nrussell6 - here is the updated DataAccess class. Let me know what you think

**Comment by mattfred** [comment]
@nrussell6 @drthvdr - I went ahead and added the `AtmLogger` class here as well. The full class is shown in the video presentation. It was just a matter of following along and copying the code.

**Comment by mattfred** [comment]
When I now run the `TestHarness` class, all tests pass :+1:

**Comment by mattfred** [comment]
@kbesser @nse710live - including you guys in the current pull request. Let me know if you see any errors or anything that needs to change before this is submitted. Once everyone gives the ok I will submit the project.

**Comment by kbesser** [comment]
Ok I'll let you know when I get a chance to look at it.

**Comment by nrussell6** [comment]
Okay, I'll be doing code review of it today and will push any changes I make tonight. By the way, I apologize for being radio silent the past few days. My other course work has left me more swamped than I anticipated. I'll do better from now on though.

**Comment by drthvdr** [comment]
I've combed through it a bit today, going back and forth from this to code reviews at work, oops! Lol but it seems good to me.. Will give it my undivided attention tonight, but nothing stood out to me that would be a problem.

**Pull request merged**
